export * from './response/Response'
export * from './proveedor/proveedor.interfaces'
export * from './proveedor/proveedor-filter.interfaces'
export * from './proveedor/proveedor-delete.interfaces'
export * from './common/select-list-descriptivas.interfaces'
export * from './comunicacion/comunicacion-response.interfaces'