-- RH.RH_V_HISTORICO_MOVIMIENTOS source

CREATE OR REPLACE FORCE VIEW "RH"."RH_V_HISTORICO_MOVIMIENTOS" ("CODIGO_PERSONA", "CEDULA", "FOTO", "NOMBRE", "APELLIDO", "NACIONALIDAD", "DESCRIPCION_NACIONALIDAD", "SEXO", "STATUS", "DESCRIPCION_STATUS", "CODIGO_EMPRESA", "DESCRIPCION_SEXO", "CODIGO_RELACION_CARGO", "CODIGO_CARGO", "CARGO_CODIGO", "CODIGO_ICP", "CODIGO_ICP_UBICACION", "SUELDO", "DESCRIPCION_CARGO", "CODIGO_TIPO_NOMINA", "TIPO_NOMINA", "FRECUENCIA_PAGO_ID", "CODIGO_SECTOR", "CODIGO_PROGRAMA", "TIPO_CUENTA_ID", "DESCRIPCION_TIPO_CUENTA", "BANCO_ID", "DESCRIPCION_BANCO", "NO_CUENTA", "EXTRA1", "EXTRA2", "EXTRA3", "USUARIO_INS", "FECHA_INS", "USUARIO_UPD", "FECHA_UPD", "CODIGO_PERIODO", "FECHA_NOMINA", "FECHA_INGRESO", "FECHA_NOMINA_MOV", "COMPLEMENTO", "TIPO", "MONTO", "ESTATUS_MOV", "CODIGO", "DENOMINACION", "CODIGO_CONCEPTO") AS
  SELECT A."CODIGO_PERSONA",A."CEDULA",A."FOTO",A."NOMBRE",A."APELLIDO",A."NACIONALIDAD",A."DESCRIPCION_NACIONALIDAD",A."SEXO",A."STATUS",A."DESCRIPCION_STATUS",A."CODIGO_EMPRESA",A."DESCRIPCION_SEXO",A."CODIGO_RELACION_CARGO",A."CODIGO_CARGO",A."CARGO_CODIGO",A."CODIGO_ICP",A."CODIGO_ICP_UBICACION",A."SUELDO",A."DESCRIPCION_CARGO",A."CODIGO_TIPO_NOMINA",A."TIPO_NOMINA",A."FRECUENCIA_PAGO_ID",A."CODIGO_SECTOR",A."CODIGO_PROGRAMA",A."TIPO_CUENTA_ID",A."DESCRIPCION_TIPO_CUENTA",A."BANCO_ID",A."DESCRIPCION_BANCO",A."NO_CUENTA",A."EXTRA1",A."EXTRA2",A."EXTRA3",A."USUARIO_INS",A."FECHA_INS",A."USUARIO_UPD",A."FECHA_UPD",A."CODIGO_PERIODO",A."FECHA_NOMINA",A."FECHA_INGRESO", B.FECHA_NOMINA FECHA_NOMINA_MOV, B.COMPLEMENTO_CONCEPTO COMPLEMENTO, B.TIPO, B.MONTO, B.STATUS ESTATUS_MOV, C.CODIGO, C.DENOMINACION, c.codigo_concepto
  FROM rh.RH_HISTORICO_PERSONAL_CARGO A, rh.RH_HISTORICO_NOMINA B, rh.RH_CONCEPTOS C
 WHERE A.CODIGO_PERSONA = B.CODIGO_PERSONA
   AND A.CODIGO_TIPO_NOMINA = B.CODIGO_TIPO_NOMINA
   AND A.CODIGO_PERIODO = B.CODIGO_PERIODO
   AND B.CODIGO_CONCEPTO = C.CODIGO_CONCEPTO
   AND B.CODIGO_TIPO_NOMINA = C.CODIGO_TIPO_NOMINA ;

   -- RH.RH_CONCEPTOS definition

CREATE TABLE "RH"."RH_CONCEPTOS"
   (	"CODIGO_CONCEPTO" NUMBER(10,0) NOT NULL ENABLE,
	"CODIGO" VARCHAR2(5),
	"CODIGO_TIPO_NOMINA" NUMBER(10,0),
	"DENOMINACION" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(1000),
	"TIPO_CONCEPTO" VARCHAR2(1),
	"MODULO_ID" NUMBER(10,0),
	"CODIGO_PUC" NUMBER(10,0),
	"STATUS" VARCHAR2(1),
	"EXTRA1" VARCHAR2(100),
	"EXTRA2" VARCHAR2(100),
	"EXTRA3" VARCHAR2(100),
	"USUARIO_INS" NUMBER(10,0),
	"FECHA_INS" DATE,
	"USUARIO_UPD" NUMBER(10,0),
	"FECHA_UPD" DATE,
	"CODIGO_EMPRESA" NUMBER(10,0),
	"FRECUENCIA_ID" NUMBER(10,0),
	"DEDUSIBLE" NUMBER(1,0) DEFAULT 0,
	"AUTOMATICO" NUMBER(1,0) DEFAULT 0,
	"ID_MODELO_CALCULO" NUMBER(10,0),
	 CHECK (AUTOMATICO IN (0,1)) ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAMI_DATA01" ;

CREATE OR REPLACE TRIGGER "RH"."RH_TRG_BEF_UPD_CONCEPTOS"
 BEFORE UPDATE OR DELETE
 ON RH_CONCEPTOS
 FOR EACH ROW
BEGIN
    Declare
        V_USUARIO varchar2(100):=null;
        V_MAQUINA varchar2(100):=null;
        V_FECHA varchar2(100) :=null;
    BEGIN
        select v.OSUSER,V.Machine,to_char(sysdate,'DD/MM/RRRR HH:MI:SS')
        into  V_USUARIO,V_MAQUINA,V_FECHA
        from v$session V Where V.AUDSID=(
        SELECT USERENV('SESSIONID') from dual);

     IF UPDATING THEN
        INSERT INTO RH.RH_H_CONCEPTOS VALUES (RH_S_CODIGO_H_CONCEPTO.NEXTVAL, SYSDATE, :NEW.USUARIO_UPD,
                                                :OLD.CODIGO_CONCEPTO,
                                                :OLD.CODIGO,
                                                :OLD.CODIGO_TIPO_NOMINA,
                                                :OLD.DENOMINACION,
                                                :OLD.DESCRIPCION,
                                                :OLD.TIPO_CONCEPTO,
                                                :OLD.MODULO_ID,
                                                :OLD.CODIGO_PUC,
                                                :OLD.STATUS,
                                                :OLD.EXTRA1,
                                                :OLD.EXTRA2,
                                                :OLD.EXTRA3,
                                                :OLD.USUARIO_INS,
                                                :OLD.FECHA_INS,
                                                :OLD.USUARIO_UPD,
                                                :OLD.FECHA_UPD,
                                                :OLD.CODIGO_EMPRESA,
                                                :OLD.FRECUENCIA_ID,
                                                :OLD.DEDUSIBLE,
                                                :OLD.AUTOMATICO, V_USUARIO,V_MAQUINA);
     ELSIF DELETING THEN
            Raise_Application_Error (-20001,'No es Permitido Delete Sobre Esta Tabla');
     END IF;
  End;
END;
/
ALTER TRIGGER "RH"."RH_TRG_BEF_UPD_CONCEPTOS" ENABLE;

CREATE UNIQUE INDEX "RH"."RH_CONCEPTOS_PK" ON "RH"."RH_CONCEPTOS" ("CODIGO_CONCEPTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAMI_DATA01" ;

CREATE UNIQUE INDEX "RH"."RH_CONCEPTOS_U2" ON "RH"."RH_CONCEPTOS" ("CODIGO", "CODIGO_TIPO_NOMINA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAMI_DATA01" ;

COMMENT ON COLUMN RH.RH_CONCEPTOS.AUTOMATICO IS '0 = no a utomatico, 1 = automatico';

-- RH.RH_TIPOS_NOMINA definition

CREATE TABLE "RH"."RH_TIPOS_NOMINA"
   (	"CODIGO_TIPO_NOMINA" NUMBER(10,0),
	"DESCRIPCION" VARCHAR2(100),
	"SIGLAS_TIPO_NOMINA" VARCHAR2(3),
	"FRECUENCIA_PAGO_ID" NUMBER(10,0),
	"EXTRA1" VARCHAR2(100),
	"EXTRA2" VARCHAR2(100),
	"EXTRA3" VARCHAR2(100),
	"USUARIO_INS" NUMBER(10,0),
	"FECHA_INS" DATE,
	"USUARIO_UPD" NUMBER(10,0),
	"FECHA_UPD" DATE,
	"CODIGO_EMPRESA" NUMBER(10,0),
	"SUELDO_MINIMO" NUMBER,
	"CODIGO_PRESUPUESTO_ACTUAL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAMI_DATA01" ;

CREATE UNIQUE INDEX "RH"."RH_TIPOS_NOMINA_U1" ON "RH"."RH_TIPOS_NOMINA" ("CODIGO_TIPO_NOMINA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SAMI_DATA01" ;
