export interface IHistoricoMovimiento{
  codigoHistoricoNomina:number
  codigoPersona:number;
  cedula:number
  foto:string;
  nombre:string;
  apellido:string;
  full_name:string
  nacionalidad:string;
  descripcionNacionalidad:string;
  sexo:string;
  status:string;
  descripcionStatus:string;
  descripcionSexo:string;
  codigoRelacionCargo:number;
  codigoCargo:number;
  cargoCodigo:string;
  codigoIcp:number;
  codigoIcpUbicacion:number;
  sueldo:number;
  descripcionCargo:string;
  codigoTipoNomina:number;
  tipoNomina:string;
  frecuenciaPagoId:number
  descripcionFrecuenciaPago:string;
  codigoSector:string;
  codigoPrograma:string;
  tipoCuentaId:number;
  descripcionTipoCuenta:string;
  bancoId:number;
  descripcionBanco:string;
  noCuenta:string;
  extra1:string;
  extra2:string;
  extra3:string;
  codigoPeriodo:number;
  fechaNomina:string;
  fechaIngreso:Date;
  fechaNominaMov:Date;
  complemento:string;
  tipo:string;
  monto:number;
  statusMov:string;
  codigo:string;
  denominacion:string;
  avatar:string;
  unidadEjecutora:string;
  estadoCivil:string;
  searchText:string;
}
